module_name: ProductVideos
compatible_versions: 1.0.0+
author: Michael Rouse
category: front office
tags:
  - product
  - videos
description_short: Add videos to your product
description: description.md
license: MIT
php_version:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
